---

- file:
    path: tempDIR
    state: directory
    mode: 0755

- file:
    path: tempDIR/AWS
    state: directory
    mode: 0755

- file:
    path: tempDIR/AZURE
    state: directory
    mode: 0755

- file:
    path: tempDIR/GOOGLE
    state: directory
    mode: 0755

- template:
    src: aws.tfvars.j2
    dest: tempDIR/AWS/variables.tfvars

- template:
    src: azure.tfvars.j2
    dest: tempDIR/AZURE/variables.tfvars

- template:
    src: google.tfvars.j2
    dest: tempDIR/GOOGLE/variables.tfvars

- template:
    src: azure.main.tf.j2
    dest: tempDIR/AZURE/main.tf

- terraform:
    project_path: "tempDIR/AZURE/"
    force_init: "false"
    variables_file: "tempDIR/AZURE/variables.tfvars"
    state: present