---

- file:
    path: tempDIR
    state: directory
    mode: 0755

- file:
    path: tempDIR/AWS
    state: directory
    mode: 0755

- file:
    path: tempDIR/AZURE
    state: directory
    mode: 0755

- file:
    path: tempDIR/GOOGLE
    state: directory
    mode: 0755

- template:
    src: aws.tfvars.j2
    dest: tempDIR/AWS/variables.tf

- template:
    src: azure.tfvars.j2
    dest: tempDIR/AZURE/variables.tf

- template:
    src: google.tfvars.j2
    dest: tempDIR/GOOGLE/variables.tf